# define the language of this project
language: node_js

# define node.js versions to run on
node_js:
  - "stable"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

stages:
  - test
  - lint
  - name: external-tools
    if: branch IN (master, develop)

jobs:
  include:
    - stage: test
      script: npm run test-travis

    - stage: lint
      node_js: stable
      script: npm run lint

    - stage: external-tools
      node_js: stable
      script:
        - npm run test-travis

        # send coverage data to coveralls
        - npm run-script coveralls
        # send coverage data to codeclimate
        - npm run-script codeclimate
        # send coverage data to codacy
        - npm run-script codacy

