# define the language of this project
language: node_js

# define node.js versions to run on
node_js:
  - "stable"
  - "9"
  - "8.9" # something is broken between Node.js v8.2 and v8.9
  - "8.3"
  - "8.2"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

# run before everey other script
before_script:
  - npm install

# run some scripts
script:
  # run lint
  - npm run-script lint

  # run tests
  - npm run-script test-travis

# trigger some additional tools after success
after_success:
  # send coverage data to coveralls
  - npm run-script coveralls
  # send coverage data to codeclimate
  - npm run-script codeclimate
  # send coverage data to codacy
  - npm run-script codacy
