# Set build version.
version: "{build}-{branch}"

environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "13"
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"

platform:
  - x86
  - x64

matrix:
  # Fail fast and stop on build errors for the current tested version.
  fast_finish: true

cache:
  - node_modules -> package.json

# Fix Git line endings on checkout
#init:
#  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  # Output used NodeJS/NPM versions
  - node --version
  - npm --version

  # run lint
  # NOTICE: let travis do the linting
#  - npm run-script lint

  # run tests
  # NOTICE: run without code coverage on appveyor -> travis handles that
  - npm run-script test-appveyor

#after_test:
#  # send coverage data to coveralls
#  - npm run-script coveralls
#
#  # send coverage data to codeclimate
#  - npm run-script codeclimate

# Don't actually build.
build: off  
