name: code-quality

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 10.x
          - 11.x
          - 12.x
          - 13.x
          - 14.x
          - 15.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    env:
      CONFIG_FILE: '../config/config.ci.json'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint
    - run: npm run test-cov
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
